version: "3.3"

services:
  taskmate:
    image: sothy/taskmate
    container_name: taskmate
    networks: 
      - swag
    ports:
      - 8000:8000
    restart: always
    
  swag:
    image: linuxserver/swag:version-1.9.0
    container_name: swag
    networks: 
      - swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/PhnomPenh
      - URL=sothy.tech
      - SUBDOMAINS=taskmate,
      - VALIDATION=http
      #- DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      # - EMAIL=<e-mail> #optional
      # - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true #optional
      # - EXTRA_DOMAINS=<extradomains> #optional
      # - STAGING=false #optional
    volumes:      
      - ./nginx/proxy-confs/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

networks:
  swag:

